core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from users.views import DashboardView

admin.site.site_header = "BOOKING Administrator"
admin.site.site_title = "BOOKING Administrator"
admin.site.index_title = "Welcome to BOOKING Administrator"

urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('', include('users.urls')),
    path('', include('services.urls')),
    path('', include('variants.urls')),
    path('', include('bookings.urls')),

    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path, include
from rest_framework import routers

from services.views import (
    ServiceListView, ServiceCreateView, ServiceUpdateView, ServiceDeleteView,
    SellerListView, SellerCreateView, SellerUpdateView, SellerDeleteView, SellerDetailView,
    CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView,
    SellerProductCreateView, SellerProductUpdateView, SellerProductDeleteView,

    ServiceListAPIView, CategoryListAPIView, SellerListAPIView, SellerDetailAPIView,
    ProductPopularListAPIView, ProductDetailAPIView, ProductSearchListAPIView,
    AddToCartView,  OrderListAPIView, OrderDetailAPIView,
    IncreaseOrderItemView, DecreaseOrderItemView,
    TableListAPIView, TimeslotListAPIView,
    BookingAPIView, BookingQueueAPIView, BookingPayAPIView, BookingListAPIView
)

urlpatterns = [
    path('seller/<slug:service_slug>/', SellerListView.as_view(), name="seller-list"),
    path('seller/<slug:service_slug>/create/', SellerCreateView.as_view(), name="seller-create"),
    path('seller/<slug:seller_slug>/update/', SellerUpdateView.as_view(), name="seller-update"),
    path('seller/<slug:seller_slug>/delete/', SellerDeleteView.as_view(), name="seller-delete"),
    path('seller/<slug:seller_slug>/detail/', SellerDetailView.as_view(), name="seller-detail"),

    path('category/<slug:service_slug>/', CategoryListView.as_view(), name="service-category-list"),
    path('category/<slug:service_slug>/create/', CategoryCreateView.as_view(), name="category-create"),
    path('category/<slug:category_slug>/update/', CategoryUpdateView.as_view(), name="category-update"),
    path('category/<slug:category_slug>/delete/', CategoryDeleteView.as_view(), name="category-delete"),

    path('product/<slug:service_slug>/', ProductListView.as_view(), name="service-product-list"),
    path('product/<slug:service_slug>/create/', ProductCreateView.as_view(), name="product-create"),
    path('product/<slug:product_slug>/update/', ProductUpdateView.as_view(), name="product-update"),
    path('product/<slug:product_slug>/delete/', ProductDeleteView.as_view(), name="product-delete"),
    path('product/<slug:product_slug>/detail/', ProductDetailView.as_view(), name="product-detail"),

    path('seller/<slug:seller_slug>/product/create/', SellerProductCreateView.as_view(), name="seller-product-create"),
    path('seller-product/<slug:product_slug>/update/', SellerProductUpdateView.as_view(), name="seller-product-update"),
    path('seller-product/<slug:product_slug>/delete/', SellerProductDeleteView.as_view(), name="seller-product-delete"),

    path('service/', ServiceListView.as_view(), name="service-list"),
    path('service/create/', ServiceCreateView.as_view(), name="service-create"),
    path('service/<int:pk>/update/', ServiceUpdateView.as_view(), name="service-update"),
    path('service/<int:pk>/delete/', ServiceDeleteView.as_view(), name="service-delete"),


    # ===========================================A=======P==P=======II================================================ #
    # ==========================================A=A======P==P=======II================================================ #
    # =========================================A===A=====P==========II================================================ #

    path('api/v1/services/', ServiceListAPIView.as_view()),
    path('api/v1/categories/<slug:slug>/', CategoryListAPIView.as_view()),
    path('api/v1/sellers/<slug:service_slug>/', SellerListAPIView.as_view()),
    path('api/v1/seller/<slug:seller_slug>/detail/', SellerDetailAPIView.as_view()),

    # Product URLs
    path('api/v1/<slug:category_slug>/products/popular/', ProductPopularListAPIView.as_view()),
    path('api/v1/products/search/', ProductSearchListAPIView.as_view()),
    path('api/v1/product/<slug:product_slug>/detail/', ProductDetailAPIView.as_view()),

    # Order URLs
    path('api/v1/order/', AddToCartView.as_view()),
    path('api/v1/order/list/', OrderListAPIView.as_view()),
    path('api/v1/seller/<slug:slug>/order/', OrderDetailAPIView.as_view()),

    # OrderItems URLs
    path('api/v1/order/increase/', IncreaseOrderItemView.as_view()),
    path('api/v1/order/decrease/', DecreaseOrderItemView.as_view()),

    # Booking URLs
    path('api/v1/booking/', BookingAPIView.as_view()),
    path('api/v1/booking/<str:status>/list/', BookingListAPIView.as_view()),
    path('api/v1/booking/<int:pk>/queue/', BookingQueueAPIView.as_view()),
    path('api/v1/booking/pay/', BookingPayAPIView.as_view()),

    path('api/v1/seller/<slug:seller_slug>/tables/', TableListAPIView.as_view()),
    path('api/v1/seller/<slug:seller_slug>/timeslots/', TimeslotListAPIView.as_view()),
    # path('api/v1/table/<int:pk>/order/', OrderDetailAPIView.as_view()),
]

services/models.py
import os
import datetime

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models import Avg

from autoslug import AutoSlugField
from core.utils import resize_image


class Service(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='services/')
    slug = AutoSlugField(populate_from='name')
    note = models.CharField(max_length=200, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('service-list')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(1000, 300), thumbnail=False)

    def __str__(self):
        return self.name


DELIVERY_TYPES = (
    ('F', 'Free Delivery'),
    ('P', 'Paid Delivery'),
)

def seller_image_path(instance, filename):
    return 'sellers/{0}/{1}'.format(instance.service.name, filename)

def category_image_path(instance, filename):
    return 'categories/{0}/{1}'.format(instance.service.name, filename)

def product_image_path(instance, filename):
    return 'products/{0}/{1}/{2}'.format(instance.seller.service.name, instance.seller.name, filename)


class Seller(models.Model):
    service = models.ForeignKey(Service, related_name="sellers", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=seller_image_path)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    description = models.TextField(null=True, blank=True)
    wait_time = models.IntegerField(default=30)
    # service_time = models.IntegerField(null=True, blank=True)   # This field is reserved. Not confirmed yet.
    open_time = models.TimeField(default=datetime.time(9, 00))
    close_time = models.TimeField(default=datetime.time(22, 00))
    delivery = models.CharField(choices=DELIVERY_TYPES, max_length=1, default='F')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return '/seller/{0}/'.format(self.service.slug)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(1000, 300), thumbnail=True)

    @property
    def thumbnail(self):
        image_path = self.image.url
        dirname = os.path.dirname(image_path)
        basename = os.path.basename(image_path)
        return os.path.join(dirname, 'thumbnail', basename)

    @property
    def rating(self):
        if self.reviews.exists():
            return float("{:.1f}".format(self.reviews.aggregate(Avg('rating'))['rating__avg']))
        return 0.0


class Category(models.Model):
    service = models.ForeignKey(Service, related_name="categories", on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to=category_image_path)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/category/{0}/'.format(self.service.slug)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(300, 300), thumbnail=False)


class Product(models.Model):
    seller = models.ForeignKey(Seller, related_name="products", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name="products", on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=product_image_path)
    price = models.DecimalField(default=0.00, max_digits=6, decimal_places=2)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/product/{0}/'.format(self.seller.service.slug)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(1000, 300), thumbnail=True)
    
    @property
    def thumbnail(self):
        image_path = self.image.url
        dirname = os.path.dirname(image_path)
        basename = os.path.basename(image_path)
        return os.path.join(dirname, 'thumbnail', basename)

services/forms.py
from django import forms

from services.models import (
    Product,
    Seller,
    Service,
    Category,
)


class SellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        exclude = ('service',)
    

class SellerProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('seller',)
    
    def __init__(self, *args, **kwargs):
        seller_slug = kwargs.pop('seller_slug')
        super().__init__(*args, **kwargs)
        seller = Seller.objects.get(slug=seller_slug)
        self.fields['category'].queryset = Category.objects.filter(service=seller.service)


class ServiceProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        service_slug = kwargs.pop('service_slug')
        super().__init__(*args, **kwargs)
        service = Service.objects.get(slug=service_slug)
        self.fields['seller'].queryset = Seller.objects.filter(service=service)
        self.fields['category'].queryset = Category.objects.filter(service=service)

services/templates/sellers/create.html
{% extends 'layouts/main.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container mt-5">
        <div class="card card-body py-5 px-5">
            <h3>Create {{ service.name }}</h3>
            <hr>

            <div class="mt-2 mb-3 bg-danger text-white rounded">
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        <span class="error-field">{{ value }}</span>
                    {% endfor %}
                {% endif %}
            </div>

            <form method="POST" enctype="multipart/form-data">
                
                {% csrf_token %}

                {{ form|crispy }}

                <div class="my-5"></div>

                <button class="btn btn-primary" type="submit">Create</button>
                <a class="btn btn-warning ml-2" href="{% url 'seller-list' service.slug %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

services/templates/sellers/delete.html
{% extends 'layouts/main.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-md">
                <div class="card card-body text-center py-4">
                    <p>Are you sure you want to delete <b>{{ object.name }}</b>?</p>

                    <form action="{% url 'seller-delete' object.slug %}" method="POST">
                        {% csrf_token %}

                        <a class="btn btn-warning mr-3" href="{% url 'seller-list' object.service.slug %}">Cancel</a>

                        <button class="btn btn-danger" type="submit">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

services/templates/sellers/detail.html
{% extends 'layouts/main.html' %}

{% block content %}
    <br>
    <div class="card card-body">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <img src="{{ object.image.url }}" alt="IMAGE" class="card-img-top">
                    <div class="card-body pt-3 pb-2">
                        <div class="row">
                            <div class="col-6">
                                <a class="btn btn-danger btn-block mb-2" href="{% url 'table-create' object.slug %}">View Tables</a>
                            </div>
                            <div class="col-6">
                                <a class="btn btn-success btn-block mb-2" href="{% url 'timeslot-create' object.slug %}">View Timeslots</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-9">
                <div class="mr-1 d-flex justify-content-between">
                    <h5 class="text-info ml-3">{{ object.name }}</h5>
                    <div>
                        <a class="btn btn-warning" href="{% url 'seller-update' object.slug %}">Change</a>
                        <a class="btn btn-primary" href="{% url 'seller-list' object.service.slug %}">Back to List</a>
                    </div>
                </div>
                <hr class="my-2">
                <p class="px-3 py-1" style="min-height: 60px;">
                    {% if object.description %}
                        {{ object.description }}
                    {% else %}
                        No description given
                    {% endif %}
                </p>
                
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-6">
                            <div class="row py-1">
                                <div class="col-3"><span class="text-primary">Service Type:</span></div>
                                <div class="col-9">{{ object.service.name }}</div>
                            </div>
                            <div class="row py-1">
                                <div class="col-3"><span class="text-primary">Address:</span></div>
                                <div class="col-9">{{ object.address }}</div>
                            </div>
                            <div class="row py-1">
                                <div class="col-3"><span class="text-primary">Phone Number:</span></div>
                                <div class="col-9">{{ object.phone }}</div>
                            </div>
                            <div class="row pt-2">
                                <div class="col-3"><span class="text-danger font-weight-bold">Rating:</span></div>
                                <div class="col-9">
                                    <a href="#">
                                        {% if object.rating > 0.0 %}
                                        <span class="text-success font-weight-bold">{{ object.rating }}</span>
                                        <span class="text-success font-weight-bold">({{ object.reviews.all|length}} Reviews)</span>
                                        {% else %}
                                        <span class="text-success font-weight-bold">No Reviews</span>
                                        {% endif %}
                                    </a>
                                </div>
                            </div>
                            
                        </div>
                        <div class="col-6">
                            <div class="row py-1">
                                <div class="col-3"><span class="text-primary">Open Time:</span></div>
                                <div class="col-9">{{ object.open_time }}</div>
                            </div>
                            <div class="row py-1">
                                <div class="col-3"><span class="text-primary">Close Time:</span></div>
                                <div class="col-9">{{ object.close_time }}</div>
                            </div>
                            <div class="row py-1">
                                <div class="col-3"><span class="text-primary">Delivery:</span></div>
                                <div class="col-9">{{ object.get_delivery_display }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-12">
            <h5 class="mt-4 mb-3 ml-2">Products</h5>
            <hr>
            <div class="row mb-2">
                <div class="col">
                    <div class="card card-body py-3 my-filter">
                        <form method="get">
                            {{ product_filter.form }}
                            <button class="btn btn-sm btn-primary" type="submit">Search Product</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="card card-body">
                <a class="btn btn-primary btn-sm btn-block mb-3 py-2 font-weight-bold"
                   href="{% url 'seller-product-create' object.slug %}">+ Add New Product</a>
                <table class="table table-sm">
                    <thead class="thead-light">
                    <tr>
                        <th>Name</th>
                        <th class="text-center">Image</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Show</th>
                        <th>Change</th>
                        <th>Delete</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for product in object_list %}
                        <tr>
                            <td>{{ product.name }}</td>
                            <td class="text-center"><img width="60" height="60" src="{{ product.image.url }}" alt="Image"></td>
                            <td>{{ product.description }}</td>
                            <td>{{ product.price }}</td>
                            <td>{{ product.category }}</td>
                            <td><a class="btn btn-sm btn-info" href="{% url 'product-detail' product.slug %}">Show</a></td>
                            <td><a class="btn btn-sm btn-warning" href="{% url 'seller-product-update' product.slug %}">Change</a></td>
                            <td><a class="btn btn-sm btn-danger" href="{% url 'seller-product-delete' product.slug %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% include "layouts/pagination.html" %}

            </div>
        </div>

        
    </div>

{% endblock %}

services/templates/sellers/list.html
{% extends 'layouts/main.html' %}

{% block content %}

    <div class="row">
        <div class="col-md">
            <h5 class="mt-5 mb-3 ml-2">{{ service.name|upper }} MANAGEMENT</h5>
            <hr>

            <br>
            <div class="card card-body">
                <a class="btn btn-primary btn-sm btn-block mb-3 py-2 font-weight-bold"
                   href="{% url 'seller-create' service.slug %}">+ Add New {{ service|title }}</a>
                <table class="table table-sm">
                    <thead class="thead-light">
                    <tr>
                        <th class="w-25">No.</th>
                        <th class="w-25">Name</th>
                        <th>Slug</th>
                        <th>Image</th>
                        <th>View</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for seller in page_obj %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ seller.name }}</td>
                            <td>{{ seller.slug}}</td>
                            <td><img src="{{ seller.image.url }}" width="100"></td>
                            <td><a class="btn btn-sm btn-info"
                                href="{% url 'seller-detail' seller.slug %}">Show</a></td>
                            <td><a class="btn btn-sm btn-warning"
                                href="{% url 'seller-update' seller.slug %}">Change</a></td>
                            <td><a class="btn btn-sm btn-danger"
                                href="{% url 'seller-delete' seller.slug %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% include "layouts/pagination.html" %}
                
            </div>
        </div>
    </div>

{% endblock %}

services/templates/sellers/update.html
{% extends 'layouts/main.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container mt-5">
        <div class="card card-body py-5 px-5">
            <h3>Update {{ object.name }} {{ object.service.name }}</h3>
            <hr>

            <div class="mt-2 mb-3 bg-danger text-white rounded">
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        <span class="error-field">{{ value }}</span>
                    {% endfor %}
                {% endif %}
            </div>

            <form method="POST" enctype="multipart/form-data">
                
                {% csrf_token %}

                {{ form|crispy }}

                <div class="my-5"></div>

                <button class="btn btn-primary" type="submit">Update</button>
                <a class="btn btn-warning ml-2" href="{% url 'seller-list' object.service.slug %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}