core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from users.views import DashboardView

admin.site.site_header = "BOOKING Administrator"
admin.site.site_title = "BOOKING Administrator"
admin.site.index_title = "Welcome to BOOKING Administrator"

urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('', include('users.urls')),
    path('', include('services.urls')),
    path('', include('variants.urls')),
    path('', include('bookings.urls')),

    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path, include
from rest_framework import routers

from services.views import (
    ServiceListView, ServiceCreateView, ServiceUpdateView, ServiceDeleteView,
    SellerListView, SellerCreateView, SellerUpdateView, SellerDeleteView, SellerDetailView,
    CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView,
    SellerProductCreateView, SellerProductUpdateView, SellerProductDeleteView,

    ServiceListAPIView, CategoryListAPIView, SellerListAPIView, SellerDetailAPIView,
    ProductPopularListAPIView, ProductDetailAPIView, ProductSearchListAPIView,
    AddToCartView,  OrderListAPIView, OrderDetailAPIView,
    IncreaseOrderItemView, DecreaseOrderItemView,
    TableListAPIView, TimeslotListAPIView,
    BookingAPIView, BookingQueueAPIView, BookingPayAPIView, BookingListAPIView
)

urlpatterns = [
    path('seller/<slug:service_slug>/', SellerListView.as_view(), name="seller-list"),
    path('seller/<slug:service_slug>/create/', SellerCreateView.as_view(), name="seller-create"),
    path('seller/<slug:seller_slug>/update/', SellerUpdateView.as_view(), name="seller-update"),
    path('seller/<slug:seller_slug>/delete/', SellerDeleteView.as_view(), name="seller-delete"),
    path('seller/<slug:seller_slug>/detail/', SellerDetailView.as_view(), name="seller-detail"),

    path('category/<slug:service_slug>/', CategoryListView.as_view(), name="service-category-list"),
    path('category/<slug:service_slug>/create/', CategoryCreateView.as_view(), name="category-create"),
    path('category/<slug:category_slug>/update/', CategoryUpdateView.as_view(), name="category-update"),
    path('category/<slug:category_slug>/delete/', CategoryDeleteView.as_view(), name="category-delete"),

    path('product/<slug:service_slug>/', ProductListView.as_view(), name="service-product-list"),
    path('product/<slug:service_slug>/create/', ProductCreateView.as_view(), name="product-create"),
    path('product/<slug:product_slug>/update/', ProductUpdateView.as_view(), name="product-update"),
    path('product/<slug:product_slug>/delete/', ProductDeleteView.as_view(), name="product-delete"),
    path('product/<slug:product_slug>/detail/', ProductDetailView.as_view(), name="product-detail"),

    path('seller/<slug:seller_slug>/product/create/', SellerProductCreateView.as_view(), name="seller-product-create"),
    path('seller-product/<slug:product_slug>/update/', SellerProductUpdateView.as_view(), name="seller-product-update"),
    path('seller-product/<slug:product_slug>/delete/', SellerProductDeleteView.as_view(), name="seller-product-delete"),

    path('service/', ServiceListView.as_view(), name="service-list"),
    path('service/create/', ServiceCreateView.as_view(), name="service-create"),
    path('service/<int:pk>/update/', ServiceUpdateView.as_view(), name="service-update"),
    path('service/<int:pk>/delete/', ServiceDeleteView.as_view(), name="service-delete"),


    # ===========================================A=======P==P=======II================================================ #
    # ==========================================A=A======P==P=======II================================================ #
    # =========================================A===A=====P==========II================================================ #

    path('api/v1/services/', ServiceListAPIView.as_view()),
    path('api/v1/categories/<slug:slug>/', CategoryListAPIView.as_view()),
    path('api/v1/sellers/<slug:service_slug>/', SellerListAPIView.as_view()),
    path('api/v1/seller/<slug:seller_slug>/detail/', SellerDetailAPIView.as_view()),

    # Product URLs
    path('api/v1/<slug:category_slug>/products/popular/', ProductPopularListAPIView.as_view()),
    path('api/v1/products/search/', ProductSearchListAPIView.as_view()),
    path('api/v1/product/<slug:product_slug>/detail/', ProductDetailAPIView.as_view()),

    # Order URLs
    path('api/v1/order/', AddToCartView.as_view()),
    path('api/v1/order/list/', OrderListAPIView.as_view()),
    path('api/v1/seller/<slug:slug>/order/', OrderDetailAPIView.as_view()),

    # OrderItems URLs
    path('api/v1/order/increase/', IncreaseOrderItemView.as_view()),
    path('api/v1/order/decrease/', DecreaseOrderItemView.as_view()),

    # Booking URLs
    path('api/v1/booking/', BookingAPIView.as_view()),
    path('api/v1/booking/<str:status>/list/', BookingListAPIView.as_view()),
    path('api/v1/booking/<int:pk>/queue/', BookingQueueAPIView.as_view()),
    path('api/v1/booking/pay/', BookingPayAPIView.as_view()),

    path('api/v1/seller/<slug:seller_slug>/tables/', TableListAPIView.as_view()),
    path('api/v1/seller/<slug:seller_slug>/timeslots/', TimeslotListAPIView.as_view()),
    # path('api/v1/table/<int:pk>/order/', OrderDetailAPIView.as_view()),
]

services/models.py
import os
import datetime

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models import Avg

from autoslug import AutoSlugField
from core.utils import resize_image


class Service(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='services/')
    slug = AutoSlugField(populate_from='name')
    note = models.CharField(max_length=200, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('service-list')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(1000, 300), thumbnail=False)

    def __str__(self):
        return self.name


DELIVERY_TYPES = (
    ('F', 'Free Delivery'),
    ('P', 'Paid Delivery'),
)

def seller_image_path(instance, filename):
    return 'sellers/{0}/{1}'.format(instance.service.name, filename)

def category_image_path(instance, filename):
    return 'categories/{0}/{1}'.format(instance.service.name, filename)

def product_image_path(instance, filename):
    return 'products/{0}/{1}/{2}'.format(instance.seller.service.name, instance.seller.name, filename)


class Seller(models.Model):
    service = models.ForeignKey(Service, related_name="sellers", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=seller_image_path)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    description = models.TextField(null=True, blank=True)
    wait_time = models.IntegerField(default=30)
    # service_time = models.IntegerField(null=True, blank=True)   # This field is reserved. Not confirmed yet.
    open_time = models.TimeField(default=datetime.time(9, 00))
    close_time = models.TimeField(default=datetime.time(22, 00))
    delivery = models.CharField(choices=DELIVERY_TYPES, max_length=1, default='F')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return '/seller/{0}/'.format(self.service.slug)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(1000, 300), thumbnail=True)

    @property
    def thumbnail(self):
        image_path = self.image.url
        dirname = os.path.dirname(image_path)
        basename = os.path.basename(image_path)
        return os.path.join(dirname, 'thumbnail', basename)

    @property
    def rating(self):
        if self.reviews.exists():
            return float("{:.1f}".format(self.reviews.aggregate(Avg('rating'))['rating__avg']))
        return 0.0


class Category(models.Model):
    service = models.ForeignKey(Service, related_name="categories", on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to=category_image_path)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/category/{0}/'.format(self.service.slug)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(300, 300), thumbnail=False)


class Product(models.Model):
    seller = models.ForeignKey(Seller, related_name="products", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name="products", on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=product_image_path)
    price = models.DecimalField(default=0.00, max_digits=6, decimal_places=2)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/product/{0}/'.format(self.seller.service.slug)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image, size=(1000, 300), thumbnail=True)
    
    @property
    def thumbnail(self):
        image_path = self.image.url
        dirname = os.path.dirname(image_path)
        basename = os.path.basename(image_path)
        return os.path.join(dirname, 'thumbnail', basename)

services/forms.py
from django import forms

from services.models import (
    Product,
    Seller,
    Service,
    Category,
)


class SellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        exclude = ('service',)
    

class SellerProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('seller',)
    
    def __init__(self, *args, **kwargs):
        seller_slug = kwargs.pop('seller_slug')
        super().__init__(*args, **kwargs)
        seller = Seller.objects.get(slug=seller_slug)
        self.fields['category'].queryset = Category.objects.filter(service=seller.service)


class ServiceProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        service_slug = kwargs.pop('service_slug')
        super().__init__(*args, **kwargs)
        service = Service.objects.get(slug=service_slug)
        self.fields['seller'].queryset = Seller.objects.filter(service=service)
        self.fields['category'].queryset = Category.objects.filter(service=service)

services/templates/services/create.html
{% extends 'layouts/main.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container mt-5">
        <div class="card card-body py-5 px-5">
            <h3>Add New Service</h3>
            <hr>

            <div class="mt-2 mb-3 bg-danger text-white rounded">
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        <span class="error-field">{{ value }}</span>
                    {% endfor %}
                {% endif %}
            </div>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form|crispy }}

                <div class="my-5"></div>

                <button class="btn btn-primary" type="submit">Create</button>
                <a class="btn btn-warning ml-2" href="{% url 'service-list' %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

services/templates/services/delete.html
{% extends 'layouts/main.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-md">
                <div class="card card-body text-center py-4">
                    <p>Are you sure you want to delete <b>{{ service.name }}</b> service?</p>

                    <form action="{% url 'service-delete' service.id %}" method="POST">
                        {% csrf_token %}

                        <a class="btn btn-warning mr-3" href="{% url 'service-list' %}">Cancel</a>

                        <button class="btn btn-danger" type="submit">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

services/templates/services/list.html
{% extends 'layouts/main.html' %}

{% block content %}

    <div class="row">
        <div class="col-md">
            <h5 class="mt-5 mb-3 ml-2">SERVICE MANAGEMENT</h5>
            <hr>

            <br>
            <div class="card card-body">
                <a class="btn btn-primary btn-sm btn-block mb-3 py-2 font-weight-bold"
                   href="{% url 'service-create' %}">+ Add New Service</a>
                <table class="table table-sm">
                    <thead class="thead-light">
                    <tr>
                        <th class="w-25">No.</th>
                        <th class="w-50">Name</th>
                        <th>Image</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for service in service_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ service.name }}</td>
                            <td><img src="{{ service.image.url }}" width="100"></td>
                            <td><a class="btn btn-sm btn-info"
                                href="{% url 'service-update' service.id %}">Change</a></td>
                            <td><a class="btn btn-sm btn-danger"
                                href="{% url 'service-delete' service.id %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
                
            </div>
        </div>
    </div>

{% endblock %}

services/templates/services/update.html
{% extends 'layouts/main.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container mt-5">
        <div class="container mt-4">
            <div class="card card-body py-5 px-5">
                <h3>Change Service</h3>
                <hr>

                <div class="mt-2 mb-3 bg-danger text-white rounded">
                    {% if form.errors %}
                        {% for key, value in form.errors.items %}
                            <span class="error-field">{{ value }}</span>
                        {% endfor %}
                    {% endif %}
                </div>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form|crispy }}

                    <div class="my-5"></div>

                    <button class="btn btn-primary" type="submit">Change</button>
                    <a class="btn btn-warning ml-2" href="{% url 'service-list' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}